apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "worldcup.fullname" . }}-config
  labels:
    {{- include "worldcup.labels" . | nindent 4 }}
data:
  DB_HOST: {{ .Values.config.DB_HOST | quote }}
  DB_PORT: {{ .Values.config.DB_PORT | quote }}
  DB_NAME: {{ .Values.config.DB_NAME | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: worldcup-initdb
  labels:
    {{- include "worldcup.labels" . | nindent 4 }}
data:
  init.sql: |
{{ .Files.Get "files/init.sql" | indent 4 }}
